# Generated by Django 3.1.4 on 2020-12-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('start_snow_water_eq', models.FloatField()),
                ('change_snow_water_eq', models.FloatField()),
                ('start_snow_depth', models.FloatField()),
                ('change_snow_depth', models.FloatField()),
            ],
        ),
    ]
