# Generated by Django 3.1.4 on 2020-12-22 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pow_pal_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state', models.CharField(max_length=100)),
                ('state_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='state',
            field=models.ForeignKey(default='WA', on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='pow_pal_api.state'),
        ),
    ]
