# Generated by Django 3.1.4 on 2020-12-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pow_pal_api', '0002_auto_20201222_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='state',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
